export const ADRESSE_DELETE_REQUEST = 'ADRESSE_DELETE_REQUEST';
export const ADRESSE_DELETE_SUCCESS = 'ADRESSE_DELETE_SUCCESS';
export const ADRESSE_DELETE_FAIL = 'ADRESSE_DELETE_FAIL';
export const ADRESSE_DELETE_RESET = 'ADRESSE_DELETE_RESET';

export const ADRESSE_LIST_REQUEST = 'ADRESSE_DETAILS_REQUEST';
export const ADRESSE_LIST_SUCCESS = 'ADRESSE_DETAILS_SUCCESS';
export const ADRESSE_LIST_FAIL = 'ADRESSE_DETAILS_FAIL';
export const ADRESSE_LIST_RESET = 'ADRESSE_DETAILS_RESET';

export const ADD_ADRESSE = 'ADD_ADRESSE';
export const GET_ADRESSE = 'GET_ADRESSE';
export const REMOVE_ADRESSE = 'REMOVE_ADRESSE';

export const ADRESSE_GET_REQUEST = 'ADRESSE_GET_REQUEST';
export const ADRESSE_GET_SUCCESS = 'ADRESSE_GET_SUCCESS';
export const ADRESSE_GET_FAIL = 'ADRESSE_GET_FAIL';

export const ADRESSE_UPDATE_REQUEST = 'ADRESSE_UPDATE_REQUEST';
export const ADRESSE_UPDATE_SUCCESS = 'ADRESSE_UPDATE_SUCCESS';
export const ADRESSE_UPDATE_FAIL = 'ADRESSE_UPDATE_FAIL';
export const ADRESSE_UPDATE_RESET = 'ADRESSE_UPDATE_RESET';


export const ADRESSE_ADD_REQUEST = 'ADRESSE_ADD_REQUEST';
export const ADRESSE_ADD_SUCCESS = 'ADRESSE_ADD_SUCCESS';
export const ADRESSE_ADD_FAIL = 'ADRESSE_ADD_FAIL';
export const ADRESSE_ADD_RESET = 'ADRESSE_ADD_RESET';

