
export const REQUEST_ADD_RETURN = 'REQUEST_ADD_RETURN';
export const SUCCESS_ADD_RETURN = 'SUCCESS_ADD_RETURN';
export const FAIL_ADD_RETURN = 'FAIL_ADD_RETURN';

export const REQUEST_GET_RETURN = 'REQUEST_GET_RETURN';
export const SUCCESS_GET_RETURN = 'SUCCESS_GET_RETURN';
export const FAIL_GET_RETURN = 'FAIL_GET_RETURN'

export const REQUEST_REMOVE_RETURN = 'REQUEST_REMOVE_RETURN';
export const SUCCESS_REMOVE_RETURN = 'SUCCESS_REMOVE_RETURN';
export const FAIL_REMOVE_RETURN = 'FAIL_REMOVE_RETURN';

